# -*- coding: utf-8 -*-
"""Thanakorn_tmd_Bkk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HuW_8pnY5FcIIc75vX-VmMp55nkGn7RF
"""

token='eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjQwNDM1YTcxNDhjYjQyYjJmZDRhNWNlOWZkM2I5NDhmMWIzODk0YmRmYmE1MGE1NGExNmU5MDdhNDM5NWIwNTcyNjQwOTdhMDJmYzdjNzUxIn0.eyJhdWQiOiIyIiwianRpIjoiNDA0MzVhNzE0OGNiNDJiMmZkNGE1Y2U5ZmQzYjk0OGYxYjM4OTRiZGZiYTUwYTU0YTE2ZTkwN2E0Mzk1YjA1NzI2NDA5N2EwMmZjN2M3NTEiLCJpYXQiOjE2MTcwMDgzNDcsIm5iZiI6MTYxNzAwODM0NywiZXhwIjoxNjQ4NTQ0MzQ3LCJzdWIiOiIxMzUxIiwic2NvcGVzIjpbXX0.QRv2bj-YTss8Cg2RF0S5Lxbo_jG2h71AfuoKdCMdigMXHHmj3dT8FzjBXWY3rSVjfOude1VdmVO_V8gD3pTP5TI8s4K8YX09K0Rt0zN1ULJPt6hFUTYc196E1xG7xuuWNkl3BT4XyoD4b7nEB389VE9bSiwYDAz9HZs_-aqO0wI6DOCCK1BG5ZE6XO9XrcBvE3pgAP5zi0VSdu_k7CtQWAQC-mXY-tGSCQASSyd-78OeqfhvYfS-xI937EniyhOMvgC6LQcRiODwp8AI8sqhLRwY5tsligAtVKETu7EnQy-J0WLHGeno-yR_3duXLG6DtC5GviBcW5x50eL8tRoAsFdRRRxTCCXPnLGU8aTlR_CAcfaan6wsyhDENQFu3n56jYaLoryd4xLOVRRuYv8MjBmV7ueJErLlgJy_CRHAvhudRHH1Sg6mANrUJMDJKXwvdI_oHFOR_fRWSU8YqNrYxNt_mxB7joTvZr0yR6jkgiu_98JFXmKepp6jg5B3bkN7DmwUi-IBD_e0tw8Lq7DDB8tn6m5DlnxgbvZJAyW6kF3RXRyVlbYVkC5eY8wFda313ETf25Di3wXRf3wuufac7PanzndmI5hYT97ubwuIUDBwMaYHSsajrOqo1Kb17sSaXUQsRECvN5_v6KKbsEoJz2jV_pVo84-SAaWk69EB9xY'

import requests
import datetime as dt
import json
url = "https://data.tmd.go.th/nwpapi/v1/forecast/location/hourly/at"

querystring = {"lat":"13.10", "lon":"100.10", "fields":"tc,rh,rain ", "date":"2021-03-23", "hour":"8", "duration":"2"}

headers = {
    'accept': "application/json",
    'authorization': "Bearer "+token,
    }

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)

import pandas as pd
df = pd.read_csv('province_list.csv')

#lat long for BKK
lat =  13.753
long = 100.5
t = dt.datetime.now()+dt.timedelta(hours=1)

url = "https://data.tmd.go.th/nwpapi/v1/forecast/location/hourly/at"

querystring = {
    "lat":"%s"%lat,
    "lon":"%s"%long,
    "fields":"tc,rh,rain",
    "date":"%s-%02d-%02d"%(t.year,t.month,t.day),
    "hour":"%s"%(t.hour),
    "duration":"1"
   }
headers = {
   'accept': "application/json",
   'authorization': "Bearer "+token,
    }

response = requests.request("GET", url, headers=headers, params=querystring)
d=json.loads(response.text)
d =  {
        'lat': d['WeatherForecasts'][0]['location']['lat'],
        'lon': d['WeatherForecasts'][0]['location']['lon'],
        'time': d['WeatherForecasts'][0]['forecasts'][0]['time'],
        'rh': d['WeatherForecasts'][0]['forecasts'][0]['data']['rh'],
        'tc': d['WeatherForecasts'][0]['forecasts'][0]['data']['tc'],
        'rain': d['WeatherForecasts'][0]['forecasts'][0]['data']['rain']
    }
df_out= pd.DataFrame(columns=['BKK','time','temperature','humidity','rain'])
#df_out = pd.read_csv('province_list.csv')
#df_out = df_out.drop(columns=['Unnamed: 0'])
df_out.loc[len(df_out)]=['BKK',d['time'],d['tc'],d['rh'],d['rain']]
df_out.to_csv('tmd_hourly.csv')